### ISSUE TITLE
[Proposal] Conflicting dependency

### ISSUE THREAD

**Issue by izayoi256** [evias/nem-php#11]
```kornrunner/keccak``` requires ```php: >=7.1``` though ```evias/nem-php``` requires ```php: >=5.5.9```.

Use [mine](https://packagist.org/packages/izayoi256/keccak) (just a copy of ```kornrunner/keccak``` for  ```php: >=5.3```), fix dependency of ```evias/nem-php```, or take other way instead please.

**Comment by evias** [comment]
ha great, i actually did a step in that way too but couldn't finalize, I will have a look at installing your version after a small review of the package.. PHP and Keccak is a hell to get working.. and very slow usually too, even the kornrunner one is slow. It is best to use extensions (c++ wrapper) for that matter but I prefered to have this library include the keccak wrapper directly.

Nevertheless, thank you for this proposal, I will have a look at this.

**Comment by jplim08** [comment]
any updates for this issue? im having error in installing this wrapper 
![Capture](https://user-images.githubusercontent.com/31497964/117623067-eb47bf00-b1a5-11eb-8249-baf6f4c0503c.PNG)

**Comment by evias** [comment]
would need to see your composer.json to be able to help ;

generally on this issue, the **dependency kornrunner/keccak** is still the used dependency, so you will need to adapt your composer.json to be compatible with it.

**Comment by jplim08** [comment]
here is my composer.json file

![Capture](https://user-images.githubusercontent.com/31497964/117784335-0a158680-b276-11eb-857b-87fe68fd7f95.PNG)

**Comment by evias** [comment]
You'd need to use this package's `master` branch, not the `0.2.14` release tag. This package has not been tagged to a later release as I do not do maintenance here anymore.

**Comment by evias** [comment]
@jplim08 my team just pushed a new tag `v0.3.0` which you should be able to use in combination with php7 and up
