### ISSUE TITLE
private key from randomly new keypair

### ISSUE THREAD

**Issue by momopaper** [evias/nem-php#13]
Hi, i tried out your 9th example to create a randomly keypair and i want to get clean private key from it, thus i assume 

`$keypair->getPrivateKey("hex")`

this line of code would give me the private key i want, but somehow i try import the result in nano wallet, it shows different address from what your code generated

can you advice me?

**Comment by evias** [comment]
the hex generated should definitely give you the same addresses, there is a unit test for that, are you sure you are using the right network to generate the address with php?

Address::fromPublicKey(pubKey, 104) for mainnet

**Comment by evias** [comment]
mhmm this is indeed a weird case, I do confirm the nano address derivation for this private key.

I will try and setup a small test case, I have used this library for other projects and never had such problems, I actually **always** make sure that nano reproduces the same address, as a first.

I will come back to you with the test case and example, thanks for pointing this out. It could be something about *how you use the classes*, maybe I have been using them differently and that's what I want to check 👍

**Comment by evias** [comment]
I believe there could be a problem with the Address::fromPublicKey algorithm, please let me know and try with :

```
$kp = KeyPair::create("1925f8049d117284ad3fb7ed8029453654613010ac887d1527fe582459da78db");

$pubKey = $kp->getPublicKey()->getHex();
$t_address = $kp->getAddress(-104); // Testnet
$n_address = $kp->getAddress(104); // Mainnet
```

**Comment by momopaper** [comment]
nice, tell me if u need anything, i can try my best to help u

**Comment by momopaper** [comment]
sorry for the late reply, 

here is the result:

pubkey:
00b3bf2f56f64d503650261102f482437a6fc3190ea0d3104b83bc42d9657b28

t_address:
TDSECQWGEHEE5AJMD4C3WGEGRWLPCZNHUY6ZNWK7

n_address:
NDSECQWGEHEE5AJMD4C3WGEGRWLPCZNHUZQJMQGZ

**Comment by evias** [comment]
Hello, I tried with a small test case and **i cannot reproduce your case**. Here is the link to the gist of the PHP used :

https://gist.github.com/evias/b30c6b8821b9c309d921188a21d44f64

I have successfully recreated **the same address as Nanowallet**.

You are probably doing something wrong with your private key before initializing the keypair.

✌️
